package com.algaworks.algafoodapi.domain.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Represents a payment method used in the system.
 * Each payment method has a unique identifier and a description.
 *
 * <p>
 * The {@code id} field is automatically generated by the database and serves
 * as the primary key for identifying payment methods.
 * </p>
 *
 * <p>
 * The {@code description} field contains a short description or name of the
 * payment method.
 * It cannot be null and should provide a clear and concise name for the payment
 * method.
 * </p>
 *
 * <p>
 * Example usage:
 * 
 * <pre>{@code
 * PaymentMethod paymentMethod = new PaymentMethod();
 * paymentMethod.setDescription("Credit Card");
 * paymentMethodRepository.save(paymentMethod);
 * }</pre>
 * </p>
 *
 * @Entity
 */
@Entity
public class PaymentMethod {

	/**
	 * The unique identifier for the payment method.
	 * This field is automatically generated by the database.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * The description or name of the payment method.
	 * It cannot be null and should provide a clear and concise name.
	 */
	@Column(nullable = false)
	private String description;

	/**
	 * Retrieves the unique identifier of the payment method.
	 *
	 * @return The payment method's unique identifier.
	 */
	public Long getId() {
		return id;
	}

	/**
	 * Sets the unique identifier of the payment method.
	 *
	 * @param id The payment method's unique identifier.
	 */
	public void setId(final Long id) {
		this.id = id;
	}

	/**
	 * Retrieves the description or name of the payment method.
	 *
	 * @return The description or name of the payment method.
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the description or name of the payment method.
	 *
	 * @param description The description or name of the payment method.
	 */
	public void setDescription(final String description) {
		this.description = description;
	}
}
